### ISSUE TITLE
Zombie organisation services

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#107]
When a org is removed services are still active because no way to remove them in Feathers. We should keep a list of dead services and filter them using a app hook.

**Comment by cnouguier** [comment]
It seems to be easier to manage with Feathers 5 : https://dove.feathersjs.com/api/services.html#teardown-app-path

**Comment by claustres** [comment]
Now available through [`app.unuse()`](https://dove.feathersjs.com/api/application.html#unuse-path).
