### ISSUE TITLE
Layer edition performance overhead in map

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#128]
Even for "simple" layers (eg 500 features) edition can become really slow if all features are visible. We should limit edition to a given zoom level and probably to features visible in the viewport.

**Comment by cnouguier** [comment]
wrong issue reference in  8075ffc

**Comment by claustres** [comment]
Now we rely on https://github.com/geoman-io/leaflet-geoman performances are pretty similar between rendering and editing. For big datasets tiling is required anyway and edition on tiled layer will only apply to currently loaded tiles.
