### ISSUE TITLE
 Standardize the behavior of all widgets

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kdk#143]
When a widget is closed, the marker should be hidden 
When a widget is opened, the marker should be restored and the view centered on the marker

**Comment by claustres** [comment]
Initiated a diagram to clarify the new workflow https://app.diagrams.net/#Hkalisio%2Fkdk%2Fmaster%2Fdocs%2Fassets%2FWidgets%20Workflow%20Diagram.drawio.
