### ISSUE TITLE
Tiled mesh layers not correctly unloaded when data is not available

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#150]
Activate a tiled mesh layer like temperature or wind at a time with available data, then switch outside the data availability time range => previous data remains displayed although the current time does not match it.

**Comment by robinbourianes-frizko** [comment]
Fixed with [this](https://github.com/kalisio/kdk/commit/3a9c68c972619b1e60eac875847bf28bf2a28a11)
I couldn't reproduce for tiled mesh layers like temperature, gust and such, only tiled wind layer.
