### ISSUE TITLE
KTextArea containing multilines or HTML is not displayed correctly anymore

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#217]
It seems that previous code handling it has been removed to use the new ellipsis classes when upgrading to Quasar v1.

However it does not use `v-html` anymore and display raw text, not sure if we can easily mix both things.

**Comment by claustres** [comment]
Maybe it would be better to integrate a [QEditor](https://quasar.dev/vue-components/editor) so that we directly generate HTML output. Indeed previous code converted `\n` from text area to HTML `br` tags in order to manage multilines, which is like a "hack".

**Comment by cnouguier** [comment]
It seems we also need to sanitize the html if we render the content using the directive `v-html` : https://quasar.dev/security/dos-and-donts#User-Input-and-the-Dangers-of-v-html
