### ISSUE TITLE
Simplify meteo model configuration in tiled layers

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#241]
Now the configuration is different for wind or mesh layers leading to specific cases to manage like [this](https://github.com/kalisio/kdk/blob/master/map/client/components/catalog/KWeatherLayersSelector.vue#L110) or [this](https://github.com/kalisio/aktnmap/blob/master/src/components/AlertForm.vue#L312).

Since having a different model for U and V wind component does not make sense we should only have a root meteo model for tiled wind layers similarly to mesh layers.

**Comment by robinbourianes-frizko** [comment]
Fixed with https://github.com/kalisio/kdk/commit/355b026a3f87e3ef11424d9874df6b27c3ab578f
