### ISSUE TITLE
Automate backups

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#26]
* [x] MongoDB backup/restore scripts (at least dump, human readable json useful ?)
* [x] Container backup on build according to flavor/version
* [x] Cron job for DB backup based on https://github.com/stefanprodan/mgob
* [ ] Cron job to backup volumes using https://github.com/istepanov/docker-backup-to-s3

eg https://github.com/kontena/mongo-backup or https://devops.datenkollektiv.de/automated-backup-of-mongodb-containers.html

**Comment by claustres** [comment]
Initiated scripts https://github.com/kalisio/aktnmap/commit/92a82148e4b86c7a7a6523c2e12df66ed02612ce

**Comment by cnouguier** [comment]
Interesting solution: https://github.com/stefanprodan/mgob

**Comment by claustres** [comment]
Automate container backup is not relevant as we use docker volumes, we could backup volumes but for now only DB data are persistent so that backup of the DB should be sufficient.

**Comment by claustres** [comment]
Might be a good idea to backup volumes using https://github.com/istepanov/docker-backup-to-s3.

**Comment by claustres** [comment]
Not relevant if we use a DaaS (https://github.com/kalisio/aktnmap/issues/3).
