### ISSUE TITLE
No data fetched for archived weather layer

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#260]
It appears that no data are fetched when requiring a past time near the current time.

For instance, this has been observed on the test infrastructure when trying to display GFS data from the current day when the current time was 9h. Requiring data at 3h correctly sends a request to AWS S3 while requiring it at 4h or 5h seems to do nothing.

**Comment by robinbourianes-frizko** [comment]
It could be a simple configuration issue.
Currently, s3 archived meteo layer is configured with a time range of 'now - 60D' -> 'now - 6H' (cf [here](https://github.com/kalisio/kano/blob/master/api/config/layers/weather-archive-layers.js#L169))
I'll fix the time range and check it's ok.

**Comment by robinbourianes-frizko** [comment]
Fixed in https://github.com/kalisio/kano/commit/98df77c87ed5714e8136259ca02368217f69a732
