### ISSUE TITLE
Improve legend to support user-defined legend

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#270]
A user can define a style depending on the features properties of his data layers but we don't display any legend so that it can be difficult to know which color maps to which value when a large number of property values is used.

**Comment by claustres** [comment]
Maybe we should implement a generic legend component using a chromajs specification fund in the layer then use it to generate a legend for user-defined layers.

**Comment by cnouguier** [comment]
closed in flavor of:

- https://github.com/kalisio/kdk/issues/615
- https://github.com/kalisio/kdk/issues/626
