### ISSUE TITLE
Refactor and homogenize the layout

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kdk#285]
The key points are the following:
* to make the layout lighter so that more space is available (notably for mobiles)
* to clean the separation between the part of the layout under activity responsibility and the part of the layout which remains stable for all activities
* to create a common basis shared between different layout components (overflow menu, activity bar, etc.)
* to make most of the layout definition possible from the application config in order to reduce code duplication

The following things are to be done:
* [x] create a generic KAction component managing route or handler
* [x] create a generic KPanel component managing a set of child components to build a bar or side nav/drawer
* [x] update the layout to make the different panels (top, bottom, left, right) configurable
* [x] update the layout to make it possible to inject custom components in pages
* [x] remove the app bar, the tabs, the search bar, the drawers and unify by relying on panels
* [x] remove the search bar and replace it with a generic KFilter component
* [x] provide a generic component to sort a collection
* [x] update the items to make the actions configurable
* [x] update the layers to make the actions configurable (this will allow to based it on permissions in apps)
* [x] remove geolocation mixin from activities and provide global functions instead
* [x] allow to easily filter configured components in drawer, panes and items
* [x] automate the modal editor routing
* [x] update team activities (configuration, items, etc.)
* [x] update the catalog to add configurable actions
* [x] enhance GUI rendering (Opener, Fab, Fab actions...)
* [x] provide theming guideline
* [x] update i18n
* [x] update docs
* [x] update tours
* [x] update tests

Some issues to be discussed/fixed:
* Cleaner use of page content to dynamically inject components, eg [KPositionIndicator](https://github.com/kalisio/kdk/blob/activity-bar/map/client/components/KPositionIndicator.vue#L61), we might make the component visibility reactive according to a target property. The problem is that the property must exist in the data of the activity prior to the mounting of the component to be reactive, a possible workaround is to add a dedicated object for this in the activity, eg `state: {}` and properties are dynamically added to it
* Need to make some properties reactive in configuration content, eg [badge label](https://github.com/kalisio/aktnmap/blob/activity-bar/config/default.js#L531) or visibility state, maybe we should use computed properties from element in the store in our components (seems to be related to the above)
* How to manage/sync modes between page and panes, eg [Akt'n'Map use case](https://github.com/kalisio/aktnmap/blob/activity-bar/config/default.js#L593)

**Comment by claustres** [comment]
Some issues to be discussed with @cnouguier:
* cleaner use of page content to dynamically inject components, eg [KPositionIndicator](https://github.com/kalisio/kdk/blob/activity-bar/map/client/components/KPositionIndicator.vue#L61)
* need to make some properties dynamic in configuration content, eg [badge label](https://github.com/kalisio/aktnmap/blob/activity-bar/config/default.js#L531)
* binding of some properties that do not seem to be used in KPanel/KContent (eg id, color, etc.)
