### ISSUE TITLE
Update dependencies across modules/apps

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kdk#39]
As the client bundle is created in apps by webpack, client dependencies in modules are only for informational purpose now. It appears to be a duplicated information with app package hard to maintain and therefore should be removed:
* [x] kCore
* [x] kTeam
* [x] kMap
* [x] kNotify
* [x] kEvent
* [x] kBilling
* [x] kApp
* [x] Kano
* [x] Akt'n'Map

Some out-of-date dependency versions should also be upgraded in modules/apps:
* [x] standard
* [x] eslint & plugins
* [x] lodash
* [x] debug
* [x] mocha
* [x] winston
* [x] fs-extra
* [x] moment
* [x] cross-env
* [x] superagent
...
* [x] to avoid the headache to maintain dependencies we might use https://greenkeeper.io to help

**Comment by claustres** [comment]
Tested Greenkeeper on kCore but it first requires to merge a PR with an out-of-range upgrade, see https://github.com/kalisio/kCore/pull/136, closing in favor of for now.
