### ISSUE TITLE
Scale-dependent visibility can't be reset + spelling mistake

### ISSUE THREAD

**Issue by kazemar** [kalisio/kdk#398]
I encounter 4 issues with the scale-dependent options :

1. Can't deactivate the scale-dependent minimum or maximum zoom. The only way is to set the minimum or the maximum to it's default value (minimum=3 or maximum=21)

2. When I'm hereafter the maximum zoom, the text (in french) says to zoom more to see the layer ("Zoomez d'avantage pour voir cette couche"), but it should be the opposite ("Zoomez moins pour voir cette couche").

3. The text in french has a little spelling mistake : should be written "davantage" instead of "d'avantage"

And to finish : not a bug, but strange behavior of the slides, when moving one the other is adapting itself
https://user-images.githubusercontent.com/6574960/121558208-c13c2380-ca15-11eb-9492-ae913a031c53.mp4

**Comment by claustres** [comment]
Closing in favor of different issues.
