### ISSUE TITLE
Use of Fontawesome as default Icon Set

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kdk#40]
The default iconSet of Quasar is material-icons but material-icons lacks some icons and sometimes we need to pick some icons from Fontawesome is richer. Why don't we use Fontawesome as the default Icon Set since it is now possible in Quasar ?

**Comment by leob** [comment]
If the look & feel of Quasar is based on Material Design then wouldn't MD icons look better (because the icons are designed for MD) ?

(by the way I don't suppose you're talking about the Icon Chooser which supports both)

**Comment by cnouguier** [comment]
New Quasar version provides the use of https://icons8.com/line-awesome. It seems to be a good alternative
We can change the icon set used by Quasar by changing the `iconSet` property in the Quasar.conf.js

**Comment by cnouguier** [comment]
SInce few months now, we switched to line awesome.
