### ISSUE TITLE
Gradient path width changes with min/max map zoom

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#424]
It appears that when decreasing the min map zoom from eg 3 to 1 the width of a gradient path increases on the map.

**Comment by cnouguier** [comment]
the scale used to render the object is depending of the projectionZoom option. By default this option is set to a function that returns a value depending on the minZoon and maxZoom: https://github.com/manubb/Leaflet.PixiOverlay/blob/master/L.PixiOverlay.js#L36

Fixing the projectionZoom to a constant value should do the trick
