### ISSUE TITLE
Option to see members not within a group

### ISSUE THREAD

**Issue by kazemar** [kalisio/kdk#445]
As a organisation owner it would be usefull to have like a fake group (called for example "Without group") showing the members who are not in a group.

Otherwise I have to manage a list in my computer to be sure that I don't forget a member in my groups.

**Comment by kazemar** [comment]
Can be done in a Group management page : https://github.com/kalisio/kdk/issues/448

**Comment by claustres** [comment]
Closing in favor of #448.
