### ISSUE TITLE
UIWebView API deprecation notice

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#47]
iOS app builds started exhibiting this notice: `ITMS-90809: Deprecated API Usage -  Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.`

IT seems that cordova people are aware and already work on this: https://github.com/apache/cordova-ios/issues/661 & https://github.com/apache/cordova-plugin-inappbrowser/issues/532.

**Comment by cnouguier** [comment]
https://github.com/apache/cordova-ios/issues/661 explains the way to fix the issue.
See https://github.com/kalisio/aktnmap/blob/master/src-cordova/config.xml.tpl to have the detailed cordova conf
