### ISSUE TITLE
Android build must target API level 28+

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kdk#49]
New Android builds of our apps (kApp, Kano, Akt'n'Map) fail due to Android SDK 27 deprecation:
```
Important: Recent APKs you have uploaded do not meet the target API level requirement. You will be prevented from releasing updates unless action is taken.

Hello Google Play Developer,

This is a reminder that starting November 1, 2019, updates to apps and games on Google Play will be required to target Android 9 (API level 28) or higher. After this date, the Play Console will prevent you from submitting new APKs with a targetSdkVersion less than 28.

Configuring your app to target a recent API level ensures that users benefit from significant security and performance improvements, while still allowing your app to run on older Android versions (down to the minSdkVersion).
```

We could either try to upgrade cordova or only increase target SDK version if possible.

**Comment by claustres** [comment]
Changing target SDK version to 28 in config xml + upgrading build-tools and SDK to version 28 as well does not work, the build then fails with the following error: `You have not accepted the license agreements of the following SDK components:  [Android SDK Platform 27]`.
