### ISSUE TITLE
Code coverage not correctly pushed to Code Climate in travis application builds

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#51]
Due to the fact that it is extracted from a container so that the target files do not exist on the host where Travis CI runs and the test reporter simply skip them.

**Comment by cnouguier** [comment]
The way we use code-climate reporter is deprecated => need to update the method

**Comment by cnouguier** [comment]
- [ ] kApp
- [ ] kano
- [ ] Akt'n'Map
