### ISSUE TITLE
Provide an elevation profile widget

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kdk#527]
It should work like the other widgets. Once the widget is activated and if a feature is selected it should perform the profile computation and display the result using a chart

**Comment by claustres** [comment]
Linked to https://github.com/kalisio/k2/issues/6.

**Comment by claustres** [comment]
Closed by https://github.com/kalisio/kdk/commit/7d579a39c8caa812d3e824c8e518cbb380ca5ea7.
