### ISSUE TITLE
Inject zoom level in layer property templates

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#572]
Useful to change styling according to the current zoom level. It will probably requires to force a layer update when the template depends on the zoom level, in a first step we could force a refresh based on the defined min zoom levels (https://github.com/kalisio/kdk/issues/545).

**Comment by robinbourianes-kalisio** [comment]
Closing issue, was mainly resolved with b19f70e356172891b28404003cef0b8db0833224
