### ISSUE TITLE
Upgrade to Quasar 2 / Vuejs 3

### ISSUE THREAD

**Issue by cnouguier** [kalisio/kdk#578]
- [x] Module "path" has been externalized for browser compatibility and cannot be accessed in client cod=> use path-browserify 
- [x] We could use https://github.com/JanGuillermo/vue3-markdown-it instead of porting KMarkdownViewer
- [x] mime-types-browser is not working with Node 16, see comment below . Must find a replacement solution : mime looks like a good candidate : https://github.com/broofa/mime
- [ ] Do we use https://github.com/Yaxian/vue3-dropzone instead of vue2-dropzone
- [x] Vue filters are no more supported: https://v3-migration.vuejs.org/breaking-changes/filters.html
- [x] The event bus API is no more supported. Event bus pattern can be replaced by using an external library implementing the event emitter interface, for example [mitt](https://github.com/developit/mitt) or [tiny-emitter](https://github.com/scottcorgan/tiny-emitter).
- [x] Must use vue-18n-next => it does not support interpolation in translation strings
- [x] Dynamic component has been changed => need to use the proxy defineAsyncComponent, see https://vuejs.org/guide/components/async.html#basic-usage
- [x] Store is no more working since Reactivity changed
- [x] v-model has also changed => need to update components and use `@update:model-value` instead of `@input`
- [x] Custom events emitted by the component need to be declared: https://vuejs.org/api/options-state.html#emits
- [x] Replace all refs by functions and remove refs resolver mixin
- [x] Tour system (https://github.com/alexandreDavid/vue3-tour fork for vue3)
- [ ] Slider (https://github.com/NightCatSama/vue-slider-component available in beta for vue3)

**Comment by cnouguier** [comment]
Comment on `path`, we have the following issue : 
```
 App •  ERROR  •  UI  in ./node_modules/mime-types/index.js

Module not found: Can't resolve imported dependency "path"
Did you forget to install it? You can run: yarn add path
```
removing `mime-types-browser` solves the issue but we need to replace this module => use [mime](https://github.com/broofa/mime)

**Comment by cnouguier** [comment]
Regarding the first point, it is due to webpack 5: https://quasar.dev/quasar-cli-webpack/handling-webpack#webpack-v5-compatibility-issues

**Comment by cnouguier** [comment]
Regarding the 8th point, it is also required to wrap the component using `markRaw` to enhance performance

**Comment by cnouguier** [comment]
Regarding the 4th point, we could try to use Quasar Uploader

**Comment by claustres** [comment]
Porting the markdown viewer was actually straightforward.
