### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#6]
Integrate an i18n module eg https://github.com/i18next/i18next or https://github.com/kazupon/vue-i18n. Let's wait also for Quasar 0.15 if they integrate already something.

Things to be done:
* translate dependencies
  * [ ] Quasar
  * [x] DropZone
  * [x] AJV
* [x] translate all client modules
* [x] translate client app
* translate server side
  * [x] event notifications > moved client side
  * [x] errors > in client based on 
      * [x] error code
      * [x] data object
  * [x] e-mails > **missing email subject injected from code**
* [x] check if working with cordova

**Comment by cnouguier** [comment]
https://github.com/panter/vue-i18next seems to be a good solution if we decide to go with i18next.

**Comment by cnouguier** [comment]
Wait to migrate to Quasar 0.15

**Comment by claustres** [comment]
Closing for now, will reopen dedicated issue when required.
