### ISSUE TITLE
Allow to manage a list of contacts

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#68]
In addition to members that are already part of the system. Probably best to create a dedicated activity instead of mixing with members. Contacts could be however added to groups like members.

Notifications for contacts should be performed through SMS (see https://github.com/kalisio/kNotify/issues/1) instead of push as they don't have the app installed (otherwise they would have been members).

We will have to take GDPR into account by at least sending an email to the contact so that he will allow us to store his personal information or maybe provide a dedicated (un)registration page in each organisation.

In order to validate the (un)subscription we should use a short token sent by SMS, we can probably rely on https://github.com/feathers-plus/feathers-authentication-management to do so.

* [x] subscribers service
* [x] subscription page
* [x] unsubscription page
* [x] subscribers activity
* [ ] validation process with token

**Comment by cnouguier** [comment]
Due to SMS pricing, we need to validate whether it is really needed to go further
