### ISSUE TITLE
Single Sign-On/Off

### ISSUE THREAD

**Issue by tristan-greffe** [kalisio/kdk#786]
This feature should allow to login using teams in a thrid-party application:
* [ ] login screen with redirect_url
* [ ] redirect to redirect_url once logged
* [ ] logout screen with redirect_url

Take care that we should use a backend route to perform the task as in the future we might exchange secrets to enhance security (eg client secret).

**Comment by claustres** [comment]
We now rely on keycloak to ensure SSO capabilities.
