### ISSUE TITLE
Find a solution to easily manage our multiple repos/modules

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#8]
* https://github.com/lerna/lerna
* https://github.com/knitjs/knit
* https://github.com/esrlabs/git-repo

**Comment by claustres** [comment]
Related read: https://hackernoon.com/one-vs-many-why-we-moved-from-multiple-git-repos-to-a-monorepo-and-how-we-set-it-up-f4abb0cfe469

**Comment by claustres** [comment]
See also https://github.com/feathersjs/feathers/issues/462.

**Comment by claustres** [comment]
For now created a small CLI to help switching: https://github.com/kalisio/cli

**Comment by cnouguier** [comment]
Since we merge the modules we close this issue
