### ISSUE TITLE
Status bar hides app bar on mobiles

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#87]
We should integrate https://github.com/apache/cordova-plugin-statusbar to control the behaviour.

**Comment by cnouguier** [comment]
Using  https://github.com/apache/cordova-plugin-statusbar fix the issue
This is more an issue related to the apps :
[ ] https://github.com/kalisio/kApp/issues/91
[ ] https://github.com/kalisio/aktnmap/issues/129
