### ISSUE TITLE
Add ability to download the result of a service query

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#88]
Useful to implement export features in applications and support large dataset (ie without managing  pagination).

We should probably rely on the storage service, we can use a temporary prefix on AWS S3 and set a lifecycle rule to ensure data will be erased after a given period of time.

A first prototype could make use of https://quasar.dev/quasar-utils/other-utils#Export-file for client-side only processing.

We could also use a similar approach to [mongo-express](https://github.com/mongo-express/mongo-express/blob/master/lib/routes/collection.js#L320) as a first step.

**Comment by claustres** [comment]
We can also use a similar approach to [mongo-express](https://github.com/mongo-express/mongo-express/blob/master/lib/routes/collection.js#L320) as a first step.

**Comment by cnouguier** [comment]
link to https://github.com/kalisio/kdk/issues/782
