### ISSUE TITLE
Allow to directly take a picture when uploading a file

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#99]
It seems that depending on the device the user needs to take a picture first then browse for it in the gallery using the KUploader, there is no "take picture action" directly available from the KUploader. However the accepted file type is OK (see https://stackoverflow.com/questions/27654005/how-to-upload-photo-from-gallery-in-android-to-a-website-with-dropzonejs).

Observed on a Samsung Galaxy S7: the take picture action is available when using the web version in Chrome but not the mobile application. Can be linked to permissions, file input attributes, web view restrictions, ...

**Comment by cnouguier** [comment]
Seems to be easier to allow to take directly a picture using the cordova-plugin-camera

**Comment by cnouguier** [comment]
We finall decided to handle the issue by developing our own function : see https://github.com/kalisio/aktnmap/issues/132
