### ISSUE TITLE
Make template context reactive and/or emit events

### ISSUE THREAD

**Issue by claustres** [kalisio/kdk#999]
Now it's a raw object but it would be better to make it reactive and/or let him emit events like the store in order to let components or applications react to changes.

Typically, changes in the template context should automatically refresh a layer relying on it.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the store implementation to make it reactive and emit events on changes. Updated both store.js and composables/store.js to achieve this functionality.

You can review changes in this commit: https://github.com/mnmnk43434/kalisio-kdk-999/commit/631a7ed746d0d81c8c02556e38255e46a80cbc75.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
